version: '3'

services:
    jupyternotes:
        build:
            context: .
            dockerfile: jupter.dockerfile
        ports:
            - "8888:8888"
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - ./:/work
            - /dev/video0:/dev/video0
            - /tmp/.X11-unix:/tmp/.X11-unix
        devices:
            - /dev/video0:/dev/video0
        deploy:
            resources:
                limits:
                    cpus: 4
                    memory: 3G
                reservations:
                    cpus: 4
                    memory: 3G